### PR TITLE
GTM event tracking with HTML data attributes

### PR DESCRIPTION
**Pull request by jjzicht**
Changed the way the data-tracking attributes for GTM should work, from 1 attribute (`data-tracking`) to 3 attributes (`data-trackingcategory`, `data-trackingaction` and `data-trackinglabel`).

### CODE REVIEW

**Comment by 7ochem** [comment]
It would have my preference to add dashes as word delimiters, so `data-tracking-category`, `data-tracking-action` and `data-tracking-label`.

This is how we always name things and would work better for possible technical solutions. Also it would make the spell checks of Chrome, PhpStorm and other tools not show squiggly lines below the words :grin:

**Comment by jjzicht** [comment]
That was also my idea, but GTM does not support this unfortunately. In order to access a data attribute, you use (for example) `gtm.element.dataset.trackingaction` in GTM. When you want a data attribute that has a `-` in it, GTM does not recognize it (i.e. `gtm.element.dataset.tracking-action` does not retrieve the value from `data-tracking-action`).

**Comment by 7ochem** [comment]
> gtm.element.dataset.tracking-action

Doesn't `gtm.element.dataset['tracking-action']` work? 
See https://stackoverflow.com/questions/7122609/how-do-i-reference-a-javascript-object-property-with-a-hyphen-in-it

**Comment by jjzicht** [comment]
Yeah, tried that but didn't work.
But, now it appears that lowerCamelCasing does work 😂 

So, `data-tracking-category` can be accessed in GTM with `gtm.element.dataset.trackingCategory`.

**Comment by mdoorschodt** [comment]
kan dit niet beoordelen, vraag maar aan jelle

**Pull request merged**
